// Image Generator - Generate images using Google Imagen API
const AWS = require('aws-sdk');
const https = require('https');
const { v4: uuidv4 } = require('uuid');

const dynamodb = new AWS.DynamoDB.DocumentClient();
const s3 = new AWS.S3();
const ssm = new AWS.SSM();

exports.handler = async (event) => {
  try {
    // Parse request body
    const body = JSON.parse(event.body);
    const { prompt, sessionId } = body;

    // Validate input
    if (!prompt || !sessionId) {
      return {
        statusCode: 400,
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*'
        },
        body: JSON.stringify({ error: 'Missing required fields: prompt, sessionId' })
      };
    }

    // Check for common celebrity/public figure names (proactive filtering)
    // Only blocking specific celebrity names, not generic terms
    const celebrityKeywords = [
      // Sports celebrities
      'neymar', 'messi', 'ronaldo', 'cristiano', 'lebron', 'michael jordan', 'kobe bryant',
      'serena williams', 'tiger woods', 'mahomes', 'brady', 'mbappe', 'haaland',
      // Entertainment celebrities
      'taylor swift', 'beyonce', 'kardashian', 'jenner', 'bieber', 'drake', 'rihanna',
      'ariana grande', 'selena gomez', 'billie eilish', 'adele', 'ed sheeran',
      // Tech/Business figures
      'elon musk', 'jeff bezos', 'bill gates', 'zuckerberg', 'steve jobs', 'tim cook',
      // Political figures
      'trump', 'biden', 'obama', 'clinton', 'putin', 'xi jinping',
      // Actors
      'tom cruise', 'brad pitt', 'leonardo dicaprio', 'will smith', 'dwayne johnson',
      'scarlett johansson', 'jennifer lawrence', 'angelina jolie', 'chris hemsworth'
    ];

    const lowerPrompt = prompt.toLowerCase();
    const foundKeyword = celebrityKeywords.find(keyword => lowerPrompt.includes(keyword));

    if (foundKeyword) {
      console.warn(`Blocked celebrity keyword in prompt: "${foundKeyword}"`);
      return {
        statusCode: 400,
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*'
        },
        body: JSON.stringify({
          error: "⚠️ Cannot generate images of celebrities or specific people. Creating such images could be used for deepfakes and is not allowed. Try using generic descriptions instead (e.g., 'a football player wearing number 10' instead of a celebrity's name).",
          blockedKeyword: foundKeyword
        })
      };
    }

    // Get Gemini API key from SSM Parameter Store
    const apiKeyParam = await ssm.getParameter({
      Name: process.env.GEMINI_API_KEY_PARAM || '/chatbot/gemini-api-key',
      WithDecryption: true
    }).promise();

    const apiKey = apiKeyParam.Parameter.Value;

    // Call Google Imagen API
    console.log('Calling Imagen API with prompt:', prompt);
    const imageResponse = await callImagenAPI(prompt, apiKey);

    // Extract base64 image from response
    const base64Image = imageResponse.predictions?.[0]?.bytesBase64Encoded;

    if (!base64Image) {
      throw new Error('No image generated by Imagen API');
    }

    // Convert base64 to buffer
    const imageBuffer = Buffer.from(base64Image, 'base64');
    const filename = `${uuidv4()}.png`;
    const s3Key = `images/${filename}`;

    // Upload image to S3
    const bucketName = process.env.S3_BUCKET;
    await s3.putObject({
      Bucket: bucketName,
      Key: s3Key,
      Body: imageBuffer,
      ContentType: 'image/png',
      Metadata: {
        prompt: prompt,
        sessionId: sessionId,
        generatedAt: new Date().toISOString()
      }
    }).promise();

    console.log(`Image uploaded to S3: ${s3Key}`);

    // Generate signed URL (valid for 1 hour)
    const signedUrl = s3.getSignedUrl('getObject', {
      Bucket: bucketName,
      Key: s3Key,
      Expires: 3600 // 1 hour
    });

    // Save metadata to DynamoDB
    const timestamp = Date.now();
    await dynamodb.put({
      TableName: process.env.DYNAMODB_TABLE || 'ChatMessages',
      Item: {
        sessionId,
        timestamp,
        prompt,
        imageKey: s3Key,
        filename,
        type: 'image'
      }
    }).promise();

    // Return successful response
    return {
      statusCode: 200,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*'
      },
      body: JSON.stringify({
        imageUrl: signedUrl,
        filename,
        prompt,
        timestamp
      })
    };
  } catch (error) {
    console.error('Error in image generator:', error);
    return {
      statusCode: 500,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*'
      },
      body: JSON.stringify({
        error: 'Failed to generate image',
        details: error.message
      })
    };
  }
};

/**
 * Call Google Imagen API to generate image
 * @param {string} prompt - Image generation prompt
 * @param {string} apiKey - Gemini API key
 * @returns {Promise<Object>} Imagen API response
 */
function callImagenAPI(prompt, apiKey) {
  return new Promise((resolve, reject) => {
    const data = JSON.stringify({
      instances: [{ prompt }],
      parameters: {
        sampleCount: 1,
        aspectRatio: "1:1",
        safetyFilterLevel: "block_some",
        personGeneration: "allow_all"
      }
    });

    const options = {
      hostname: 'generativelanguage.googleapis.com',
      path: '/v1beta/models/imagen-4.0-generate-001:predict',
      method: 'POST',
      headers: {
        'x-goog-api-key': apiKey,
        'Content-Type': 'application/json',
        'Content-Length': data.length
      }
    };

    const req = https.request(options, (res) => {
      let body = '';
      res.on('data', (chunk) => body += chunk);
      res.on('end', () => {
        try {
          const response = JSON.parse(body);
          if (res.statusCode === 200) {
            resolve(response);
          } else {
            // Provide better error messages for common issues
            let errorMsg = response.error?.message || 'Unknown error';
            const lowerErrorMsg = errorMsg.toLowerCase();

            // Check for celebrity/deepfake/person-related blocks
            if (lowerErrorMsg.includes('person') ||
                lowerErrorMsg.includes('face') ||
                lowerErrorMsg.includes('celebrity') ||
                lowerErrorMsg.includes('public figure') ||
                lowerErrorMsg.includes('deepfake') ||
                lowerErrorMsg.includes('identity')) {
              errorMsg = "⚠️ Cannot generate this image. Creating images of specific people or celebrities could be used for deepfakes and is not allowed. Try using generic descriptions instead (e.g., 'a football player' instead of a specific person's name).";
            }
            // Check for general safety/policy blocks
            else if (lowerErrorMsg.includes('safety') ||
                     lowerErrorMsg.includes('blocked') ||
                     lowerErrorMsg.includes('policy') ||
                     lowerErrorMsg.includes('violation')) {
              errorMsg = '⚠️ Image generation blocked by safety filters. Please try a different prompt that does not include harmful, inappropriate, or copyrighted content.';
            }
            // Check for inappropriate content
            else if (lowerErrorMsg.includes('inappropriate') ||
                     lowerErrorMsg.includes('offensive') ||
                     lowerErrorMsg.includes('harmful')) {
              errorMsg = '⚠️ This prompt contains inappropriate content and cannot be generated. Please use respectful and safe prompts.';
            }

            console.error('Imagen API Error:', JSON.stringify(response, null, 2));
            reject(new Error(errorMsg));
          }
        } catch (e) {
          reject(new Error('Failed to parse Imagen API response'));
        }
      });
    });

    req.on('error', (error) => {
      reject(new Error(`Network error: ${error.message}`));
    });

    req.write(data);
    req.end();
  });
}
